# Generated by Django 2.2.6 on 2019-10-23 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fornow.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='City name')),
            ],
            options={
                'verbose_name': 'Cities of Kazakhstan',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=150, verbose_name='Regions of Kazakhstan')),
            ],
            options={
                'verbose_name': 'Regions of Kazakhstan',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created time of Tour')),
                ('title', models.CharField(max_length=150, verbose_name='Tour title')),
                ('text', models.TextField()),
                ('duration', models.CharField(choices=[('2-3', '2-3 hours'), ('5-6', '5-6 hours'), ('7-9', '7-9 hours'), ('9-12', '9-12 hours'), ('12-24', '12-24 hours'), ('1-2', '1-2 days')], max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornow.City')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tour creater')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornow.Region')),
            ],
            options={
                'verbose_name': 'Tour of the site',
            },
        ),
        migrations.CreateModel(
            name='TypeOfTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_tour_name', models.CharField(max_length=150, verbose_name='What Type of tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fornow.models.content_file_name)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornow.Tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='type_of_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornow.TypeOfTour'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornow.Region'),
        ),
    ]
