# Generated by Django 2.2.6 on 2019-10-25 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fornow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourimage',
            options={'verbose_name': 'Tours Images model'},
        ),
        migrations.AlterModelOptions(
            name='typeoftour',
            options={'verbose_name': 'Types of Tour'},
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fornow.Tour'),
        ),
        migrations.CreateModel(
            name='TourComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_created_data', models.DateTimeField(auto_now_add=True, verbose_name='Time of when comment was added')),
                ('comment_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_creater', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fornow.Tour')),
            ],
        ),
    ]
