# Generated by Django 2.2.6 on 2020-03-28 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fornow', '0003_auto_20200328_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_title', models.CharField(max_length=100, verbose_name='review title')),
                ('review_created_data', models.DateTimeField(auto_now_add=True, verbose_name='Time of when review was added')),
                ('review_rating', models.IntegerField(verbose_name='Review Rating')),
                ('review_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_creator', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='fornow.Tour')),
            ],
        ),
        migrations.DeleteModel(
            name='TourComments',
        ),
    ]
