# Generated by Django 2.2.6 on 2020-03-29 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fornow', '0004_auto_20200328_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('tg', 'tenge'), ('$ USA', 'Dollars USA'), ('€', 'Euro')], default='tenge', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourreview',
            name='review_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_price', models.IntegerField()),
                ('booking_status_id', models.CharField(choices=[('Reserved', 'Reserved'), ('Waiting for payment', 'Waiting for payment'), ('Approved', 'Approved')], max_length=50)),
                ('booking_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Booking user')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tour', to='fornow.Tour')),
                ('travel_agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornow.ToursTravelAgent')),
            ],
        ),
    ]
