# Generated by Django 2.2.6 on 2020-03-29 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0005_auto_20200329_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_status_id',
            new_name='booking_status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_creator', to=settings.AUTH_USER_MODEL, verbose_name='Booking user'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_travel_agent', to='fornow.ToursTravelAgent'),
        ),
        migrations.AlterField(
            model_name='tourreview',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fornow.Tour'),
        ),
    ]
