# Generated by Django 2.2.6 on 2020-03-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0006_auto_20200329_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='age_requirments',
            new_name='age_requirements',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_agent_id',
        ),
        migrations.AddField(
            model_name='tour',
            name='travel_agent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_travel_agent', to='fornow.ToursTravelAgent'),
            preserve_default=False,
        ),
    ]
