# Generated by Django 2.2.6 on 2020-03-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0008_auto_20200329_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='age_requirements',
            field=models.CharField(choices=[('12 years and older', '12'), ('16  years and older', '16'), ('18  years and older', '18'), ('21  years and older', '21')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(choices=[('2 days', '2-3 days'), ('5 days', '5-6 days'), ('7 days', '7-9 days'), ('9 days', '9-12 days'), ('12 days', '12-24 days')], max_length=50),
        ),
    ]
