# Generated by Django 2.2.6 on 2020-04-02 18:18

from django.db import migrations, models
import fornow.models


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0009_auto_20200329_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimage',
            name='file',
            field=models.ImageField(upload_to=fornow.models.content_file_name),
        ),
    ]
