# Generated by Django 2.2.6 on 2020-05-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0013_auto_20200502_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotel_name',
            field=models.CharField(max_length=150, verbose_name='Hotel name'),
        ),
        migrations.AlterField(
            model_name='tourdetails',
            name='tour_start_date',
            field=models.DateField(),
        ),
    ]
