# Generated by Django 2.2.6 on 2020-05-02 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0014_auto_20200502_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourdetails',
            options={'verbose_name': 'Tour Details'},
        ),
        migrations.RemoveField(
            model_name='tourdetails',
            name='tour_end_city',
        ),
        migrations.RemoveField(
            model_name='tourdetails',
            name='tour_start_city',
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_end_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_end', to='fornow.City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourdetails',
            name='cur_person_number',
            field=models.IntegerField(default=0, null=True, verbose_name='Current Number of persons for one Tour'),
        ),
    ]
