# Generated by Django 2.2.6 on 2020-05-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0015_auto_20200502_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsimages',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='fornow.Hotels'),
        ),
    ]
