# Generated by Django 2.2.6 on 2020-05-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0017_auto_20200502_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tour',
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_detail',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='booking_tour', to='fornow.TourDetails'),
            preserve_default=False,
        ),
    ]
