# Generated by Django 2.2.6 on 2020-05-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0018_auto_20200502_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_number_of_persons',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
