# Generated by Django 2.2.6 on 2020-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0019_booking_booking_number_of_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotel_description',
            field=models.TextField(default='Hotel Descriptions', verbose_name='Hotel description'),
            preserve_default=False,
        ),
    ]
