# Generated by Django 2.2.6 on 2020-05-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0020_hotels_hotel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
