# Generated by Django 2.2.6 on 2020-05-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0021_tour_tour_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='type_of_tour',
        ),
        migrations.AddField(
            model_name='typeoftour',
            name='tour',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='type_tour', to='fornow.Tour', verbose_name='Tour'),
            preserve_default=False,
        ),
    ]
