# Generated by Django 2.2.6 on 2020-05-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0022_auto_20200509_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeoftour',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='type_of_tour',
            field=models.ManyToManyField(to='fornow.TypeOfTour'),
        ),
    ]
