# Generated by Django 2.2.6 on 2020-05-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornow', '0023_auto_20200509_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidedServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150, verbose_name='Kind of services')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='provided_services',
            field=models.ManyToManyField(to='fornow.ProvidedServices'),
        ),
    ]
